# Generated by Django 6.0.2 on 2026-03-26 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('step', '0002_alter_attachment_options_alter_attendance_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={},
        ),
        migrations.AlterModelOptions(
            name='group',
            options={},
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={},
        ),
        migrations.AlterModelOptions(
            name='performance',
            options={},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={},
        ),
        migrations.AddField(
            model_name='lesson',
            name='homework_file',
            field=models.FileField(blank=True, null=True, upload_to='lessons/hw/', verbose_name='Файл ДЗ'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='topic_file',
            field=models.FileField(blank=True, null=True, upload_to='lessons/topics/', verbose_name='Файл темы'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Присутствовал'),
        ),
        migrations.AlterField(
            model_name='group',
            name='classroom',
            field=models.CharField(max_length=50, verbose_name='Аудитория'),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название группы'),
        ),
        migrations.AlterField(
            model_name='group',
            name='schedule_time',
            field=models.CharField(max_length=100, verbose_name='Время занятий'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='date',
            field=models.DateField(verbose_name='Дата занятия'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='homework_description',
            field=models.TextField(blank=True, verbose_name='Домашнее задание'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='topic',
            field=models.TextField(verbose_name='Тема урока'),
        ),
        migrations.AlterField(
            model_name='performance',
            name='classwork_score',
            field=models.IntegerField(default=0, verbose_name='Балл в классе (0-10)'),
        ),
        migrations.AlterField(
            model_name='performance',
            name='homework_score',
            field=models.IntegerField(default=0, verbose_name='Балл за ДЗ (0-10)'),
        ),
        migrations.AlterField(
            model_name='student',
            name='level',
            field=models.IntegerField(default=1, verbose_name='Уровень'),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=100, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='student',
            name='rank',
            field=models.CharField(blank=True, max_length=50, verbose_name='Ранг'),
        ),
        migrations.AlterField(
            model_name='student',
            name='xp',
            field=models.IntegerField(default=0, verbose_name='Очки опыта (XP)'),
        ),
        migrations.DeleteModel(
            name='Attachment',
        ),
    ]
