# Generated by Django 6.0.2 on 2026-03-26 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('step', '0003_alter_attendance_options_alter_group_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='level',
            field=models.IntegerField(default=0, verbose_name='Уровень'),
        ),
    ]
