# Generated by Django 6.0.2 on 2026-03-26 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('step', '0004_alter_student_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='rank',
            field=models.CharField(blank=True, choices=[('Странник', 'Странник'), ('Ученик', 'Ученик'), ('Искатель', 'Искатель'), ('Опытный', 'Опытный'), ('Мастер', 'Мастер'), ('Магистр', 'Магистр'), ('Легенда', 'Легенда')], max_length=50, verbose_name='Ранг'),
        ),
    ]
