# Generated by Django 6.0.2 on 2026-03-27 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('step', '0007_lesson_parent_topic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='level',
        ),
    ]
