# Generated by Django 6.0.2 on 2026-03-27 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('step', '0008_remove_student_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='rank',
        ),
    ]
